<#
    scripts/subscriptions.ps1 -- `ytdl --subscribe`, the subscription
    commands, and the hourly schedule.

    Three things are defended here.

    THE STORED COMMAND LINE. A subscription is a `ytdl` command line kept
    for later, and the one way it can go wrong without anybody noticing is
    by being stored differently from how it was typed: an alias resolved
    the wrong way, a relative path that means somewhere else when the
    schedule runs it from another directory, a proxy password printed back
    in a listing. The tests store command lines and read back exactly what
    was kept, then run it and read back exactly what yt-dlp was asked for.

    THE RUNNER'S MANNERS. A scheduled check must not start while you are
    downloading, must not run twice at once, must not re-check what is not
    due, and must say what happened in a form the three apps can read. Each
    of those is a lock or a comparison that only fails under the
    circumstances it guards, so each test builds those circumstances: a
    second process holding the lock, a clock that has not moved.

    THE OPERATING-SYSTEM TEXT. The systemd units, the launchd plist and the
    Task Scheduler XML are generated by pure functions, extracted from the
    shipped file and run here on whatever platform the suite runs on. Two
    of the three can never be installed on the machine that normally runs
    this suite, so this is the only place their mistakes can be caught
    before a user's machine refuses them. The plist test exists because the
    first draft had "--" inside an XML comment, which makes the whole file
    unparseable and launchctl refuse it.

    No network, and nothing is registered with the real operating system:
    systemctl and loginctl are stubbed and XDG_CONFIG_HOME points into the
    test root for the one test that installs.
#>

Describe 'ytdl subscriptions' {

    $downloadBehavior = {
        if ($StubArgs -contains '--version') { Write-Output '2026.08.20'; return }
        if ($StubArgs -contains '-U')        { Write-Output 'yt-dlp is up to date'; return }
        if ($env:YTDLP_TEST_SLOW_MARKER) {
            Set-Content -LiteralPath $env:YTDLP_TEST_SLOW_MARKER -Value 'running'
            Start-Sleep -Seconds 4
        }
        Write-Output '[youtube] testVideo01: Downloading webpage'
        Write-Output '[youtube] testVideo01: Downloading tv player API JSON'
        if ($env:YTDLP_TEST_EMIT_ERROR -eq '1') {
            Write-Output 'ERROR: [youtube] testVideo02: Video unavailable'
        }
    }

    function New-SubsRoot {
        param([string]$Label)
        $r = New-TestRoot -Label $Label
        Install-PipelineInto -TestRoot $r -RepoRoot $script:RepoRoot
        Enable-Stubs -TestRoot $r
        New-StubBinary -TestRoot $r -Name 'yt-dlp' -Behavior $downloadBehavior | Out-Null
        # The once-a-day dependency check would otherwise run yt-dlp -U, a
        # package-manager query and an HTTPS call to GitHub per test.
        Set-Content -LiteralPath (Join-Path $r.InstallRoot '.last_dependency_check') `
                    -Value (Get-Date -Format 'o') -Encoding utf8
        return $r
    }

    function Invoke-Ytdl {
        param($Root, [AllowEmptyCollection()][string[]]$Arguments)
        return Invoke-YtdlLauncher -TestRoot $Root -Arguments $Arguments
    }

    function Read-Store {
        param($Root)
        $p = Join-Path $Root.InstallRoot 'configs/subscriptions.json'
        if (-not (Test-Path -LiteralPath $p)) { return $null }
        return (Get-Content -LiteralPath $p -Raw | ConvertFrom-Json)
    }

    function Get-Subs {
        param($Root)
        $s = Read-Store $Root
        if (-not $s) { return @() }
        return @($s.subscriptions)
    }

    # A second process holding one of the locks, for as long as a test
    # needs. -EncodedCommand rather than -Command, because -ArgumentList
    # joins its elements with spaces into one string and the path has to
    # survive that intact.
    function Start-LockHolder {
        param([string]$Path, [ValidateSet('Shared', 'Exclusive')][string]$Kind, [int]$Seconds = 30)
        $ready = "$Path.holder-ready"
        Remove-Item -LiteralPath $ready -Force -ErrorAction SilentlyContinue
        $access = if ($Kind -eq 'Shared') { 'Read' } else { 'ReadWrite' }
        $share  = if ($Kind -eq 'Shared') { 'ReadWrite' } else { 'None' }
        $cmd = "`$fs = [System.IO.File]::Open('$Path', 'OpenOrCreate', '$access', '$share'); " +
               "Set-Content -LiteralPath '$ready' -Value x; Start-Sleep -Seconds $Seconds; `$fs.Dispose()"
        $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($cmd))
        $p = Start-Process -FilePath (Get-PwshPath) -ArgumentList @('-NoProfile', '-EncodedCommand', $encoded) -PassThru
        $deadline = (Get-Date).AddSeconds(30)
        while (-not (Test-Path -LiteralPath $ready)) {
            if ((Get-Date) -gt $deadline) { $p | Stop-Process -Force -ErrorAction SilentlyContinue; throw "lock holder for $Path never became ready" }
            Start-Sleep -Milliseconds 100
        }
        return $p
    }

    $channel = 'https://www.youtube.com/@SomeChannel/videos'

    It 'stores the command line a download would have run, resolved rather than as typed' {
        $r = New-SubsRoot -Label 'subs-store'
        try {
            $cookies = Join-Path $r.Root 'cookies.txt'
            Set-Content -LiteralPath $cookies -Value '# Netscape HTTP Cookie File'
            Push-Location $r.Root
            try {
                # A relative --cookies path, a relative positional data root,
                # and --no-audio: three things that must not be stored as
                # typed.
                $res = Invoke-Ytdl $r @($channel, 'archive-here', '--sync', '--no-audio', '--quality', '720',
                                        '--cookies', 'cookies.txt', '--subscribe', '--every', '2d', '--name', 'Some Channel')
            } finally { Pop-Location }
            Assert-Equal 0 $res.ExitCode ($res.Output -join "`n")
            Assert-Match 'Subscribed [0-9a-f]{8}: Some Channel' $res.Output

            $subs = Get-Subs $r
            Assert-Equal 1 $subs.Count
            $s = $subs[0]
            Assert-Equal $channel $s.url
            Assert-Equal 'Some Channel' $s.name
            Assert-Equal 48 $s.every_hours
            Assert-True $s.enabled
            Assert-Equal ([System.IO.Path]::GetFullPath((Join-Path $r.Root 'archive-here'))) $s.data_root `
                'a relative data root must be stored absolute: the schedule does not run from this directory'
            $opts = @($s.options)
            $expected = '--sync --mode video-only --quality 720 --cookies ' + [System.IO.Path]::GetFullPath($cookies)
            Assert-Equal $expected ($opts -join ' ') `
                'the stored options must be the PARSED ones: alias resolved, cookie path absolute, --path apart'
            Assert-True ($opts -notcontains '--path') '--path belongs in data_root, not in the options'
            Assert-True ($opts -notcontains '--subscribe') 'the subscription flags are not download options'
            Assert-Equal $null $s.last_run
            Assert-True ([long]$s.added -gt 1700000000) 'timestamps are Unix seconds'
        } finally { Remove-TestRoot $r }
    }

    It 'says --sync is missing, because without it every check walks the whole listing' {
        $r = New-SubsRoot -Label 'subs-nosync'
        try {
            $res = Invoke-Ytdl $r @($channel, '--subscribe')
            Assert-Equal 0 $res.ExitCode
            Assert-Match 'without --sync' $res.Output
            $res2 = Invoke-Ytdl $r @($channel, '--sync', '--subscribe')
            Assert-NotMatch 'without --sync' $res2.Output
        } finally { Remove-TestRoot $r }
    }

    It 'replaces the options when the same URL is subscribed into the same data root again' {
        $r = New-SubsRoot -Label 'subs-replace'
        try {
            Invoke-Ytdl $r @($channel, '--sync', '--quality', '1080', '--subscribe', '--every', '6h') | Out-Null
            $first = (Get-Subs $r)[0]
            Start-Sleep -Milliseconds 1100
            $res = Invoke-Ytdl $r @($channel, '--sync', '--mode', 'audio-only', '--subscribe')
            Assert-Match 'Updated subscription' $res.Output
            $subs = Get-Subs $r
            Assert-Equal 1 $subs.Count 'the same URL and data root is the same subscription'
            Assert-Equal $first.id $subs[0].id
            Assert-Equal $first.added $subs[0].added 'when it was added does not change'
            Assert-Equal '--sync --mode audio-only' (@($subs[0].options) -join ' ')
            Assert-Equal 6 $subs[0].every_hours 'an interval not given again is kept, not reset to the default'
        } finally { Remove-TestRoot $r }
    }

    It 'keeps one channel subscribed into two data roots as two subscriptions' {
        $r = New-SubsRoot -Label 'subs-tworoots'
        try {
            Invoke-Ytdl $r @($channel, '--path', (Join-Path $r.Root 'a'), '--sync', '--subscribe') | Out-Null
            Invoke-Ytdl $r @($channel, '--path', (Join-Path $r.Root 'b'), '--sync', '--mode', 'audio-only', '--subscribe') | Out-Null
            $subs = Get-Subs $r
            Assert-Equal 2 $subs.Count
            Assert-NotEqual $subs[0].id $subs[1].id
        } finally { Remove-TestRoot $r }
    }

    It 'refuses what a subscription cannot mean, and stores nothing' {
        $r = New-SubsRoot -Label 'subs-refuse'
        try {
            foreach ($case in @(
                @{ Args = @($channel, '--probe', '--subscribe');                            Pattern = 'probe downloads nothing' },
                @{ Args = @($channel, '--mode', 'comments-only', '--refresh', '--subscribe'); Pattern = 'cannot store --refresh' },
                @{ Args = @($channel, '--every', '6h');                                     Pattern = 'only apply with --subscribe' },
                @{ Args = @($channel, '--name', 'x');                                       Pattern = 'only apply with --subscribe' },
                @{ Args = @($channel, '--paused');                                          Pattern = 'only apply with --subscribe' },
                @{ Args = @($channel, '--subscribe', '--every', '30m');                     Pattern = 'from 1h to 30d' },
                @{ Args = @($channel, '--subscribe', '--every', '31d');                     Pattern = 'from 1h to 30d' },
                @{ Args = @($channel, '--subscribe', '--every', '0h');                      Pattern = 'from 1h to 30d' },
                @{ Args = @($channel, '--subscribe', '--name', "two`nlines");               Pattern = 'one line' },
                # A bad DOWNLOAD option is refused exactly as a download
                # would refuse it -- the whole point of subscribing through
                # the same parser.
                @{ Args = @($channel, '--codec', 'av1', '--subscribe');                     Pattern = 'spelled with a zero' }
            )) {
                $res = Invoke-Ytdl $r $case.Args
                Assert-Equal 1 $res.ExitCode "should refuse: $($case.Args -join ' ')"
                Assert-Match $case.Pattern $res.Output
            }
            Assert-Equal 0 @(Get-Subs $r).Count 'nothing refused may be stored'
        } finally { Remove-TestRoot $r }
    }

    It 'lists as the documented JSON, and never shows a proxy password' {
        $r = New-SubsRoot -Label 'subs-json'
        try {
            Invoke-Ytdl $r @($channel, '--sync', '--proxy', 'socks5://me:hunter2@127.0.0.1:1080', '--subscribe', '--paused') | Out-Null
            $res = Invoke-Ytdl $r @('--subscriptions', '--json')
            Assert-Equal 0 $res.ExitCode
            $doc = ($res.Output -join "`n") | ConvertFrom-Json
            Assert-Equal 1 $doc.subscriptions_version
            Assert-True ($doc.now -is [long] -or $doc.now -is [int]) 'now is Unix seconds'
            foreach ($k in @('mechanism', 'supported', 'installed', 'active', 'running', 'next_check', 'linger', 'detail')) {
                Assert-True ($doc.schedule.PSObject.Properties.Name -contains $k) "schedule.$k is part of the contract"
            }
            $s = @($doc.subscriptions)[0]
            foreach ($k in @('id', 'url', 'name', 'options', 'data_root', 'every_hours', 'enabled', 'added', 'updated', 'last_run', 'next_due', 'due')) {
                Assert-True ($s.PSObject.Properties.Name -contains $k) "subscriptions[].$k is part of the contract"
            }
            Assert-False $s.enabled
            Assert-False $s.due 'a paused subscription is never due'
            Assert-Equal $null $s.next_due 'a paused subscription has no next check'
            Assert-Equal 'socks5://***@127.0.0.1:1080' @($s.options)[2]
            Assert-NotMatch 'hunter2' $res.Output

            $text = Invoke-Ytdl $r @('--subscriptions')
            Assert-NotMatch 'hunter2' $text.Output 'the terminal listing masks it too'
            Assert-Match 'paused' $text.Output

            # But the store keeps the real value -- a scheduled run needs it.
            Assert-Match 'hunter2' (Get-Content -Raw -LiteralPath (Join-Path $r.InstallRoot 'configs/subscriptions.json'))
            if (-not $IsWindows) {
                $mode = (& stat -c '%a' (Join-Path $r.InstallRoot 'configs/subscriptions.json') 2>$null)
                if (-not $mode) { $mode = (& stat -f '%Lp' (Join-Path $r.InstallRoot 'configs/subscriptions.json')) }
                Assert-Equal '600' "$mode".Trim() 'the store can hold a proxy password, so only its owner may read it'
            }
        } finally { Remove-TestRoot $r }
    }

    It 'prints one parseable document on stdout even with no subscriptions at all' {
        $r = New-SubsRoot -Label 'subs-empty'
        try {
            $res = Invoke-Ytdl $r @('--subscriptions', '--json')
            Assert-Equal 0 $res.ExitCode
            $doc = ($res.Output -join "`n") | ConvertFrom-Json
            Assert-Equal 0 @($doc.subscriptions).Count
            Assert-PathMissing (Join-Path $r.InstallRoot 'configs/subscriptions.json') 'listing must not create the store'
        } finally { Remove-TestRoot $r }
    }

    It 'edits the interval, the name and the pause state, and nothing else' {
        $r = New-SubsRoot -Label 'subs-edit'
        try {
            Invoke-Ytdl $r @($channel, '--sync', '--quality', '480', '--subscribe') | Out-Null
            $id = (Get-Subs $r)[0].id
            $res = Invoke-Ytdl $r @('--edit-subscription', $id, '--every', '12h', '--name', '-leading hyphen', '--pause')
            Assert-Equal 0 $res.ExitCode ($res.Output -join "`n")
            $s = (Get-Subs $r)[0]
            Assert-Equal 12 $s.every_hours
            Assert-Equal '-leading hyphen' $s.name 'a name starting with "-" must survive pwsh -File'
            Assert-False $s.enabled
            Assert-Equal '--sync --quality 480' (@($s.options) -join ' ') 'editing never touches the download options'

            Assert-Equal 0 (Invoke-Ytdl $r @('--edit-subscription', $id, '--resume')).ExitCode
            Assert-True (Get-Subs $r)[0].enabled

            foreach ($bad in @(
                @('--edit-subscription', $id),
                @('--edit-subscription', $id, '--pause', '--resume'),
                @('--edit-subscription', $id, '--quality', '720'),
                @('--edit-subscription', 'nosuchid', '--pause')
            )) {
                Assert-Equal 1 (Invoke-Ytdl $r $bad).ExitCode "should refuse: $($bad -join ' ')"
            }
        } finally { Remove-TestRoot $r }
    }

    It 'unsubscribes by id or by URL, and leaves the archive alone' {
        $r = New-SubsRoot -Label 'subs-unsub'
        try {
            Invoke-Ytdl $r @($channel, '--sync', '--subscribe') | Out-Null
            Invoke-Ytdl $r @('https://www.youtube.com/@Other/videos', '--sync', '--subscribe') | Out-Null
            $id = (Get-Subs $r)[0].id
            $res = Invoke-Ytdl $r @('--unsubscribe', $id)
            Assert-Equal 0 $res.ExitCode
            Assert-Match 'Everything it archived stays' $res.Output
            Assert-Equal 1 @(Get-Subs $r).Count
            Assert-Equal 0 (Invoke-Ytdl $r @('--unsubscribe', 'https://www.youtube.com/@Other/videos')).ExitCode
            Assert-Equal 0 @(Get-Subs $r).Count
            $miss = Invoke-Ytdl $r @('--unsubscribe', 'deadbeef')
            Assert-Equal 1 $miss.ExitCode
            Assert-Match "no subscription 'deadbeef'" $miss.Output
        } finally { Remove-TestRoot $r }
    }

    It 'refuses a store it cannot read rather than writing an empty one over it' {
        $r = New-SubsRoot -Label 'subs-corrupt'
        try {
            $store = Join-Path $r.InstallRoot 'configs/subscriptions.json'
            Set-Content -LiteralPath $store -Value '{ "subscriptions_version": 1, "subscriptions": [ { broken'
            $res = Invoke-Ytdl $r @($channel, '--sync', '--subscribe')
            Assert-Equal 1 $res.ExitCode
            Assert-Match 'not valid JSON' $res.Output
            Assert-Match 'broken' (Get-Content -Raw -LiteralPath $store) 'the file must be left exactly as it was'

            Set-Content -LiteralPath $store -Value '{ "subscriptions_version": 99, "subscriptions": [] }'
            $res = Invoke-Ytdl $r @('--subscriptions')
            Assert-Equal 1 $res.ExitCode
            Assert-Match 'newer pipeline' $res.Output
        } finally { Remove-TestRoot $r }
    }

    It 'runs a due subscription with its stored options, into its own session log' {
        $r = New-SubsRoot -Label 'subs-run'
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--quality', '720', '--subscribe') | Out-Null
            $id = (Get-Subs $r)[0].id
            Clear-StubCalls -TestRoot $r

            $res = Invoke-Ytdl $r @('--run-subscriptions')
            Assert-Equal 0 $res.ExitCode ($res.Output -join "`n")
            Assert-Match "\[subscriptions\] Checking $id" $res.Output
            # The child's own output comes through unprefixed, so a frontend
            # running this in its queue sees an ordinary session.
            Assert-Match '(?m)^-- Session summary: 1 video\(s\) touched' $res.Output

            $dl = @(Get-StubCalls -TestRoot $r -Name 'yt-dlp' | Where-Object { $_.line -match '--config-location' })
            Assert-Equal 1 $dl.Count 'exactly one download session'
            Assert-Match '--break-on-existing' $dl[0].line '--sync was stored and must reach yt-dlp'
            Assert-Match 'height<=720' $dl[0].line '--quality was stored and must reach yt-dlp'
            Assert-Match ([regex]::Escape($channel)) $dl[0].line

            $logs = Join-Path $r.DataRoot 'Archive Logs/Logs'
            Assert-PathExists (Join-Path $logs 'download.subscriptions.log')
            Assert-FileMatches (Join-Path $logs 'download.subscriptions.log') "URL: $([regex]::Escape($channel))"
            Assert-PathMissing (Join-Path $logs 'download.log') 'a scheduled session must not write the manual session log'

            $s = (Get-Subs $r)[0]
            Assert-Equal 'ok' $s.last_run.result
            Assert-Equal 1 $s.last_run.touched
            Assert-Equal 0 $s.last_run.exit_code
            Assert-Equal 'schedule' $s.last_run.trigger
            Assert-True ([long]$s.last_run.finished -ge [long]$s.last_run.started)

            Assert-FileMatches (Join-Path $r.InstallRoot 'Archive Logs/Logs/subscriptions.log') "$id\s+ok\s+touched=1"
        } finally { Remove-TestRoot $r }
    }

    It 'does not check again before it is due, but does when asked by id or for all' {
        $r = New-SubsRoot -Label 'subs-due'
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--subscribe', '--every', '6h') | Out-Null
            $id = (Get-Subs $r)[0].id
            Invoke-Ytdl $r @('--run-subscriptions') | Out-Null
            Clear-StubCalls -TestRoot $r

            $again = Invoke-Ytdl $r @('--run-subscriptions')
            Assert-Equal 0 $again.ExitCode
            Assert-Match 'Nothing is due' $again.Output
            Assert-Equal 0 @(Get-StubCalls -TestRoot $r -Name 'yt-dlp' | Where-Object { $_.line -match '--config-location' }).Count

            $doc = ((Invoke-Ytdl $r @('--subscriptions', '--json')).Output -join "`n") | ConvertFrom-Json
            $row = @($doc.subscriptions)[0]
            Assert-False $row.due
            Assert-Equal ([long]$row.last_run.started + 6 * 3600) ([long]$row.next_due)

            $byId = Invoke-Ytdl $r @('--run-subscriptions', $id)
            Assert-Equal 0 $byId.ExitCode
            Assert-Equal 'manual' (Get-Subs $r)[0].last_run.trigger
            $all = Invoke-Ytdl $r @('--run-subscriptions', 'all')
            Assert-Equal 0 $all.ExitCode
            Assert-Equal 2 @(Get-StubCalls -TestRoot $r -Name 'yt-dlp' | Where-Object { $_.line -match '--config-location' }).Count

            Assert-Equal 1 (Invoke-Ytdl $r @('--run-subscriptions', 'all', $id)).ExitCode 'all and ids together is refused'
            Assert-Equal 1 (Invoke-Ytdl $r @('--run-subscriptions', 'nosuch')).ExitCode
        } finally { Remove-TestRoot $r }
    }

    It 'counts a slack of half the heartbeat, so a daily check does not drift an hour a day' {
        $r = New-SubsRoot -Label 'subs-slack'
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--subscribe', '--every', '24h') | Out-Null
            $storePath = Join-Path $r.InstallRoot 'configs/subscriptions.json'
            $doc = Get-Content -Raw -LiteralPath $storePath | ConvertFrom-Json
            $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
            # Last started 23h40m ago: due, because the next tick would be
            # 24h40m. Written straight into the store, the one way to move
            # time for a child process.
            $doc.subscriptions[0].last_run = [pscustomobject]@{
                started = $now - (23 * 3600 + 40 * 60); finished = $now - (23 * 3600); result = 'ok'; exit_code = 0
                touched = 0; skipped = 1; errors = 0; warnings = 0; trigger = 'schedule'; message = $null
            }
            $doc | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $storePath
            $row = @(((Invoke-Ytdl $r @('--subscriptions', '--json')).Output -join "`n" | ConvertFrom-Json).subscriptions)[0]
            Assert-True $row.due '20 minutes early is inside the slack'

            $doc.subscriptions[0].last_run.started = $now - (23 * 3600)
            $doc | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $storePath
            $row = @(((Invoke-Ytdl $r @('--subscriptions', '--json')).Output -join "`n" | ConvertFrom-Json).subscriptions)[0]
            Assert-False $row.due 'an hour early is not'
        } finally { Remove-TestRoot $r }
    }

    It 'skips a paused subscription unless it is named' {
        $r = New-SubsRoot -Label 'subs-paused'
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--subscribe', '--paused') | Out-Null
            $id = (Get-Subs $r)[0].id
            Assert-Match 'Nothing is due' (Invoke-Ytdl $r @('--run-subscriptions')).Output
            Assert-Match 'No subscriptions are enabled' (Invoke-Ytdl $r @('--run-subscriptions', 'all')).Output
            $named = Invoke-Ytdl $r @('--run-subscriptions', $id)
            Assert-Equal 0 $named.ExitCode
            Assert-Equal 'ok' (Get-Subs $r)[0].last_run.result
        } finally { Remove-TestRoot $r }
    }

    It 'holds the download marker for exactly as long as a session runs' {
        $r = New-SubsRoot -Label 'subs-marker'
        $proc = $null
        $savedRoot = $env:YTDLP_INSTALL_ROOT
        try {
            $marker = Join-Path $r.Root 'slow-started'
            $env:YTDLP_TEST_SLOW_MARKER = $marker
            $env:YTDLP_INSTALL_ROOT = $r.InstallRoot
            $out = Join-Path $r.Root 'bg.out'
            # -EncodedCommand for the same quoting reason as Start-LockHolder.
            $cmd = "& '$(Join-Path $r.InstallRoot 'scripts/run_ytdlp.ps1')' -Url 'https://youtu.be/testVideo01' -DataRoot '$($r.DataRoot)'"
            $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($cmd))
            $proc = Start-Process -FilePath (Get-PwshPath) -PassThru -RedirectStandardOutput $out `
                -ArgumentList @('-NoProfile', '-EncodedCommand', $encoded)
            $deadline = (Get-Date).AddSeconds(60)
            while (-not (Test-Path -LiteralPath $marker)) {
                if ((Get-Date) -gt $deadline) { throw 'the stub never started' }
                Start-Sleep -Milliseconds 100
            }
            $lockPath = Join-Path $r.InstallRoot '.session.lock'
            $busy = $false
            try { ([System.IO.File]::Open($lockPath, 'OpenOrCreate', 'ReadWrite', 'None')).Dispose() } catch { $busy = $true }
            Assert-True $busy 'an exclusive open must fail while a session is running'
            $proc.WaitForExit(60000) | Out-Null
            $free = $true
            try { ([System.IO.File]::Open($lockPath, 'OpenOrCreate', 'ReadWrite', 'None')).Dispose() } catch { $free = $false }
            Assert-True $free 'and succeed once it has finished'
        } finally {
            $env:YTDLP_TEST_SLOW_MARKER = $null
            $env:YTDLP_INSTALL_ROOT = $savedRoot
            if ($proc -and -not $proc.HasExited) { $proc | Stop-Process -Force }
            Remove-TestRoot $r
        }
    }

    It 'leaves scheduled checks for later while another download is running' {
        $r = New-SubsRoot -Label 'subs-defer'
        $holder = $null
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--subscribe') | Out-Null
            Invoke-Ytdl $r @('https://www.youtube.com/@Other/videos', '--path', $r.DataRoot, '--sync', '--subscribe') | Out-Null
            Clear-StubCalls -TestRoot $r
            $holder = Start-LockHolder -Path (Join-Path $r.InstallRoot '.session.lock') -Kind Shared

            $res = Invoke-Ytdl $r @('--run-subscriptions')
            Assert-Equal 0 $res.ExitCode 'deferring is the expected outcome, not a failure'
            Assert-Match 'A download is running; leaving 2 due subscription' $res.Output
            Assert-Equal 0 @(Get-StubCalls -TestRoot $r -Name 'yt-dlp' | Where-Object { $_.line -match '--config-location' }).Count
            Assert-True (@(Get-Subs $r | Where-Object { $null -ne $_.last_run }).Count -eq 0) 'nothing ran, so nothing is recorded -- both stay due'
            Assert-FileMatches (Join-Path $r.InstallRoot 'Archive Logs/Logs/subscriptions.log') 'deferred 2'

            # Asked for by name, it runs anyway: that is somebody at the
            # keyboard, the same as a second terminal.
            $named = Invoke-Ytdl $r @('--run-subscriptions', 'all')
            Assert-Equal 0 $named.ExitCode
            Assert-Equal 2 @(Get-StubCalls -TestRoot $r -Name 'yt-dlp' | Where-Object { $_.line -match '--config-location' }).Count
        } finally {
            if ($holder -and -not $holder.HasExited) { $holder | Stop-Process -Force }
            Remove-TestRoot $r
        }
    }

    It 'refuses to start a second check while one is running' {
        $r = New-SubsRoot -Label 'subs-busy'
        $holder = $null
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--subscribe') | Out-Null
            $holder = Start-LockHolder -Path (Join-Path $r.InstallRoot '.subscriptions-run.lock') -Kind Exclusive
            $res = Invoke-Ytdl $r @('--run-subscriptions', 'all')
            Assert-Equal 3 $res.ExitCode
            Assert-Match 'already running' $res.Output
            $doc = ((Invoke-Ytdl $r @('--subscriptions', '--json')).Output -join "`n") | ConvertFrom-Json
            Assert-True $doc.schedule.running 'the listing says a check is running'
        } finally {
            if ($holder -and -not $holder.HasExited) { $holder | Stop-Process -Force }
            Remove-TestRoot $r
        }
    }

    It 'tells a check that found errors from a check that failed' {
        $r = New-SubsRoot -Label 'subs-errors'
        try {
            Invoke-Ytdl $r @($channel, '--path', $r.DataRoot, '--sync', '--subscribe') | Out-Null
            $env:YTDLP_TEST_EMIT_ERROR = '1'
            try { $res = Invoke-Ytdl $r @('--run-subscriptions') } finally { $env:YTDLP_TEST_EMIT_ERROR = $null }
            Assert-Equal 0 $res.ExitCode 'a session that ran to the end is not a failed run'
            $lr = (Get-Subs $r)[0].last_run
            Assert-Equal 'errors' $lr.result
            Assert-Equal 1 $lr.errors
            Assert-Equal $null $lr.message

            # A stored option that this pipeline no longer accepts: ytdl.ps1
            # re-validates on every run, so the check FAILS, and says why.
            $storePath = Join-Path $r.InstallRoot 'configs/subscriptions.json'
            $doc = Get-Content -Raw -LiteralPath $storePath | ConvertFrom-Json
            $doc.subscriptions[0].options = @('--codec', 'av1')
            $doc | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $storePath
            $bad = Invoke-Ytdl $r @('--run-subscriptions', 'all')
            Assert-Equal 1 $bad.ExitCode
            $lr = (Get-Subs $r)[0].last_run
            Assert-Equal 'failed' $lr.result
            Assert-Equal 1 $lr.exit_code
            Assert-Match 'spelled with a zero' $lr.message
            Assert-Match 'FAILED' (Invoke-Ytdl $r @('--subscriptions')).Output
        } finally { Remove-TestRoot $r }
    }

    It 'generates systemd units that quote what systemd would otherwise expand' {
        $region = Get-ScriptRegion -Path (Join-Path $script:RepoRoot 'scripts/subscriptions.ps1') `
                                   -StartMarker '# >>> SCHEDULE TEXT GENERATORS' -EndMarker '# <<< SCHEDULE TEXT GENERATORS'
        . ([scriptblock]::Create($region))
        $u = Get-SystemdUnitText -PwshPath '/opt/pwsh 7/pwsh' -YtdlScript '/home/u/100%/$HOME/a"b\c/ytdl.ps1' -PathValue '/p%:/q$'
        Assert-Match '(?m)^Type=oneshot$' $u.Service
        Assert-Match '(?m)^ExecStart="/opt/pwsh 7/pwsh" "-NoProfile" "-File" "/home/u/100%%/\$\$HOME/a\\"b\\\\c/ytdl\.ps1" "--run-subscriptions"$' $u.Service `
            '% and $ doubled, quote and backslash escaped, every word quoted'
        Assert-Match '(?m)^Environment="PATH=/p%%:/q\$"$' $u.Service '$ is literal in Environment=, % is not'
        Assert-NotMatch 'YTDLP_INSTALL_ROOT' $u.Service 'the default install root needs no override'
        $o = Get-SystemdUnitText -PwshPath '/p' -YtdlScript '/s' -PathValue '/x' -InstallRootOverride '/srv/ytdl'
        Assert-Match '(?m)^Environment="YTDLP_INSTALL_ROOT=/srv/ytdl"$' $o.Service
        foreach ($line in @('OnCalendar=hourly', 'Persistent=true', 'RandomizedDelaySec=300', 'WantedBy=timers.target')) {
            Assert-Match "(?m)^$([regex]::Escape($line))$" $u.Timer
        }

        if (Test-HasCommand 'systemd-analyze') {
            $dir = Join-Path ([System.IO.Path]::GetTempPath()) ("ytdl-units-" + [guid]::NewGuid().ToString('N').Substring(0, 8))
            New-Item -ItemType Directory -Path $dir | Out-Null
            try {
                $real = Get-SystemdUnitText -PwshPath (Get-PwshPath) -YtdlScript '/home/u/100%/$HOME/a"b\c/ytdl.ps1' -PathValue '/usr/bin:/bin'
                Set-Content -LiteralPath (Join-Path $dir 'ytdl-subscriptions.service') -Value $real.Service -NoNewline
                Set-Content -LiteralPath (Join-Path $dir 'ytdl-subscriptions.timer') -Value $real.Timer -NoNewline
                Push-Location $dir
                try { $v = & systemd-analyze verify ./ytdl-subscriptions.timer ./ytdl-subscriptions.service 2>&1 } finally { Pop-Location }
                Assert-Equal 0 $LASTEXITCODE "systemd-analyze verify refused the units: $($v -join ' ')"
            } finally { Remove-Item -LiteralPath $dir -Recurse -Force -ErrorAction SilentlyContinue }
        }
    }

    It 'generates a launchd plist that parses, with the command as separate arguments' {
        $region = Get-ScriptRegion -Path (Join-Path $script:RepoRoot 'scripts/subscriptions.ps1') `
                                   -StartMarker '# >>> SCHEDULE TEXT GENERATORS' -EndMarker '# <<< SCHEDULE TEXT GENERATORS'
        . ([scriptblock]::Create($region))
        $text = Get-LaunchdPlistText -Label 'io.github.avimehandru.ytdl-subscriptions' -PwshPath '/usr/local/bin/pwsh' `
                    -YtdlScript '/Users/a b/yt-dlp & <co>/scripts/ytdl.ps1' -PathValue '/opt/homebrew/bin:/usr/bin' `
                    -ErrorLogPath '/Users/a b/err.log'
        # The XML-comment bug: "--" inside <!-- --> makes the whole file
        # unparseable, and launchctl refuses it.
        $xml = [xml]$text
        # DocumentElement rather than $xml.plist: the DOCTYPE node is ALSO
        # named plist, so member access returns both.
        $dict = $xml.DocumentElement.dict
        Assert-Equal 'io.github.avimehandru.ytdl-subscriptions' $dict.string[0]
        $argv = @($dict.array.string)
        Assert-Equal 5 $argv.Count
        Assert-Equal '/Users/a b/yt-dlp & <co>/scripts/ytdl.ps1' $argv[3] 'escaped on the way in, intact on the way out'
        Assert-Equal '--run-subscriptions' $argv[4]
        Assert-Match '<key>StartInterval</key>\s*<integer>3600</integer>' $text
        Assert-Match '<key>PATH</key>\s*<string>/opt/homebrew/bin:/usr/bin</string>' $text
        if ($IsMacOS -and (Test-HasCommand 'plutil')) {
            $f = Join-Path ([System.IO.Path]::GetTempPath()) "ytdl-test-$([guid]::NewGuid().ToString('N')).plist"
            Set-Content -LiteralPath $f -Value $text -NoNewline
            try { & plutil -lint $f | Out-Null; Assert-Equal 0 $LASTEXITCODE 'plutil -lint' } finally { Remove-Item -LiteralPath $f -Force }
        }
    }

    It 'generates Task Scheduler XML that parses and does not kill a long check' {
        $region = Get-ScriptRegion -Path (Join-Path $script:RepoRoot 'scripts/subscriptions.ps1') `
                                   -StartMarker '# >>> SCHEDULE TEXT GENERATORS' -EndMarker '# <<< SCHEDULE TEXT GENERATORS'
        . ([scriptblock]::Create($region))
        $text = Get-TaskXmlText -PwshPath 'C:\Program Files\PowerShell\7\pwsh.exe' -YtdlScript 'C:/yt-dlp/scripts/ytdl.ps1' `
                    -UserId 'PC\avi' -StartBoundary '2026-09-24T13:00:00'
        $xml = [xml]$text
        $t = $xml.Task
        Assert-Equal 'PT1H' $t.Triggers.TimeTrigger.Repetition.Interval
        Assert-Equal 'PT0S' $t.Settings.ExecutionTimeLimit 'the default 72h limit KILLS a long first check'
        Assert-Equal 'IgnoreNew' $t.Settings.MultipleInstancesPolicy
        Assert-Equal 'true' $t.Settings.StartWhenAvailable
        Assert-Equal 'false' $t.Settings.DisallowStartIfOnBatteries
        Assert-Equal 'InteractiveToken' $t.Principals.Principal.LogonType 'no stored password'
        Assert-Equal 'PC\avi' $t.Principals.Principal.UserId
        Assert-Equal 'C:\Program Files\PowerShell\7\pwsh.exe' $t.Actions.Exec.Command
        Assert-Equal '-NoProfile -WindowStyle Hidden -File "C:/yt-dlp/scripts/ytdl.ps1" --run-subscriptions' $t.Actions.Exec.Arguments

        $o = [xml](Get-TaskXmlText -PwshPath 'p.exe' -YtdlScript "D:\it's\ytdl.ps1" -UserId 'u' -StartBoundary '2026-01-01T00:00:00' -InstallRootOverride "D:\it's")
        Assert-Match ([regex]::Escape("`$env:YTDLP_INSTALL_ROOT='D:\it''s'")) $o.Task.Actions.Exec.Arguments `
            'a non-default install root is set on the command line, single quotes doubled'
    }

    It 'builds the scheduled PATH from the current one plus the install directories, without duplicates' {
        $region = Get-ScriptRegion -Path (Join-Path $script:RepoRoot 'scripts/subscriptions.ps1') `
                                   -StartMarker '# >>> SCHEDULE TEXT GENERATORS' -EndMarker '# <<< SCHEDULE TEXT GENERATORS'
        . ([scriptblock]::Create($region))
        $sep = [System.IO.Path]::PathSeparator
        $v = Get-SchedulePathValue -CurrentPath "/usr/bin$sep/bin$sep/usr/bin" -Extra @('/home/u/.local/bin', '/bin')
        Assert-Equal "/usr/bin$sep/bin$sep/home/u/.local/bin" $v
    }

    It 'installs and removes the systemd timer through systemctl, and never touches the real one' {
        if (-not $IsLinux) { Skip-Test 'the systemd path is Linux-only; the other two are covered by their generators.' }
        $r = New-SubsRoot -Label 'subs-install'
        $savedXdg = $env:XDG_CONFIG_HOME
        try {
            $env:XDG_CONFIG_HOME = Join-Path $r.Root 'xdg'
            New-StubBinary -TestRoot $r -Name 'systemctl' -Behavior {
                $unit = Join-Path $env:XDG_CONFIG_HOME 'systemd/user/ytdl-subscriptions.timer'
                if ($StubArgs -contains 'is-active') { if (Test-Path -LiteralPath $unit) { Write-Output 'active'; exit 0 } else { Write-Output 'inactive'; exit 3 } }
                if ($StubArgs -contains 'show') { Write-Output 'NextElapseUSecRealtime=@1790006400'; exit 0 }
                exit 0
            } | Out-Null
            New-StubBinary -TestRoot $r -Name 'loginctl' -Behavior { Write-Output 'no'; exit 0 } | Out-Null

            $res = Invoke-Ytdl $r @('--schedule', 'install')
            Assert-Equal 0 $res.ExitCode ($res.Output -join "`n")
            $unitDir = Join-Path $env:XDG_CONFIG_HOME 'systemd/user'
            Assert-PathExists (Join-Path $unitDir 'ytdl-subscriptions.service')
            Assert-PathExists (Join-Path $unitDir 'ytdl-subscriptions.timer')
            Assert-FileMatches (Join-Path $unitDir 'ytdl-subscriptions.service') ([regex]::Escape((Join-Path $r.InstallRoot 'scripts/ytdl.ps1')))
            Assert-FileMatches (Join-Path $unitDir 'ytdl-subscriptions.service') 'YTDLP_INSTALL_ROOT=' 'a test install root is an override, and must be carried'
            $calls = @(Get-StubCalls -TestRoot $r -Name 'systemctl' | ForEach-Object { $_.line })
            Assert-True ($calls -contains '--user daemon-reload') "daemon-reload was not called: $($calls -join ' | ')"
            Assert-True ($calls -contains '--user enable --now ytdl-subscriptions.timer') "enable --now was not called: $($calls -join ' | ')"
            Assert-Match 'loginctl enable-linger' $res.Output 'with linger off, say that checks stop at logout'

            $st = ((Invoke-Ytdl $r @('--schedule', 'status', '--json')).Output -join "`n") | ConvertFrom-Json
            Assert-True $st.installed
            Assert-True $st.active
            Assert-Equal 1790006400 $st.next_check
            Assert-Equal $false $st.linger

            Clear-StubCalls -TestRoot $r
            $rm = Invoke-Ytdl $r @('--schedule', 'remove')
            Assert-Equal 0 $rm.ExitCode
            Assert-PathMissing (Join-Path $unitDir 'ytdl-subscriptions.timer')
            Assert-PathMissing (Join-Path $unitDir 'ytdl-subscriptions.service')
            $calls = @(Get-StubCalls -TestRoot $r -Name 'systemctl' | ForEach-Object { $_.line })
            Assert-True ($calls -contains '--user disable --now ytdl-subscriptions.timer') "disable --now was not called: $($calls -join ' | ')"
            Assert-Match 'nothing to remove' (Invoke-Ytdl $r @('--schedule', 'remove')).Output 'removing twice is not an error'

            # --dry-run writes nothing and runs nothing.
            Clear-StubCalls -TestRoot $r
            $dry = Invoke-Ytdl $r @('--schedule', 'install', '--dry-run')
            Assert-Equal 0 $dry.ExitCode
            Assert-Match 'OnCalendar=hourly' $dry.Output
            Assert-PathMissing (Join-Path $unitDir 'ytdl-subscriptions.timer')
            Assert-Equal 0 @(Get-StubCalls -TestRoot $r -Name 'systemctl').Count
        } finally {
            $env:XDG_CONFIG_HOME = $savedXdg
            Remove-TestRoot $r
        }
    }

    It 'takes the subscription commands only in the first position, with their own arguments' {
        $r = New-SubsRoot -Label 'subs-grammar'
        try {
            foreach ($bad in @(
                @('--subscriptions', '--verbose'),
                @('--unsubscribe'),
                @('--unsubscribe', 'a', 'b'),
                @('--schedule'),
                @('--schedule', 'start'),
                @('--schedule', 'status', '--dry-run'),
                @('--schedule', 'install', '--json'),
                @('--run-subscriptions', '--json')
            )) {
                $res = Invoke-Ytdl $r $bad
                Assert-Equal 1 $res.ExitCode "should refuse: $($bad -join ' ')"
                Assert-NotMatch 'first argument must be the URL' $res.Output 'these are commands, not a missing URL'
            }
            Assert-Match '--subscribe' (Invoke-Ytdl $r @()).Output 'the usage text lists them'
            Assert-Match '--run-subscriptions' (Invoke-Ytdl $r @()).Output
        } finally { Remove-TestRoot $r }
    }

    It 'says so when the install predates subscriptions, rather than failing obscurely' {
        $r = New-SubsRoot -Label 'subs-old'
        try {
            Remove-Item -LiteralPath (Join-Path $r.InstallRoot 'scripts/subscriptions.ps1') -Force
            foreach ($a in @(@('--subscriptions'), @($channel, '--subscribe'))) {
                $res = Invoke-Ytdl $r $a
                Assert-Equal 1 $res.ExitCode
                Assert-Match 'predates subscriptions' $res.Output
            }
        } finally { Remove-TestRoot $r }
    }

    It 'agrees with ytdl.ps1 about the default install root' {
        $subsText = Get-Content -Raw -LiteralPath (Join-Path $script:RepoRoot 'scripts/subscriptions.ps1')
        foreach ($rootLiteral in @('"C:/yt-dlp"', 'Join-Path $HOME "yt-dlp"', 'YTDLP_INSTALL_ROOT')) {
            Assert-True ($subsText -like "*$rootLiteral*") "subscriptions.ps1 is missing the install root $rootLiteral"
        }
    }
}
